Repository Wikia/ad-products, pull requests merged in 2018-08, with the labels that each got.

#133 ADEN-7515 Get consent data from window.__cmp in A9 bidder
  .eslintrc.json
  examples/bidders/a9/index.html
  examples/bidders/a9/script.js
  src/bidders/a9/index.js
Labels: Patch change

#134 ADEN-7362 Update ad-engine to v12.1.1
  package-lock.json
  package.json
Labels: Patch change

#135 ADEN-7526 Add advertisement label and make sure outstream starts in viewport only
  examples/context.js
  examples/templates/outstream/index.html
  package-lock.json
  package.json
  src/styles/_porvata.scss
  src/templates/interface/video/floating.js
  src/templates/outstream/porvata-template.js
Labels: Patch change

#138 ADEN-7458 Update dependencies
  examples/context.js
  package-lock.json
  package.json
Labels: Major change

#136 ADEN-7471 Make sure stickiness is launched once slot is ready
  examples/templates/hivi-uap-sticky-bfab/script.js
  src/templates/uap/themes/hivi/hivi-bfab.js
Labels: Patch change

#139 ADEN-7458-2 Update dependencies
  package-lock.json
  package.json
Labels: Patch change

#140 ADEN-7458-3 Update dependencies
  package-lock.json
  package.json
Labels: Patch change

#141 ADEN-7458-4 Fix missing ad-slot class
  src/templates/outstream/porvata-template.js
Labels: Patch change

#137 ADEN-7457 Add bid key-vals to Porvata3.
  examples/templates/outstream/index.html
  examples/templates/outstream/script.js
  src/bidders/prebid/adapters/wikia-video.js
  src/bidders/prebid/index.js
  src/bidders/prebid/prebid-settings.js
Labels: Minor change

#143 ADEN-7471-2 Add top-conflict slot status. Disable sticky flyout anima…
  dist/ad-products.amd.js
  dist/ad-products.amd.js.map
  dist/ad-products.global.js
  dist/ad-products.global.js.map
  dist/ad-products.js
  dist/ad-products.js.map
  dist/global-bundle.js
  src/templates/uap/themes/hivi/hivi-bfab.js
Labels: Patch change

#145 ADEN-7577 Set slot stickiness state.
  dist/ad-products.amd.js
  dist/ad-products.amd.js.map
  dist/ad-products.css.map
  dist/ad-products.global.js
  dist/ad-products.global.js.map
  dist/ad-products.js
  dist/ad-products.js.map
  dist/global-bundle.js
  package-lock.json
  package.json
  src/templates/uap/themes/hivi/hivi-bfab.js
Labels: Patch change

#146 ADEN-7566 Increase maxCpm to $50 for AppNexus and Rubicon videos.
  dist/ad-products.css.map
  dist/bidders.amd.js
  dist/bidders.global.js
  dist/bidders.js
  dist/global-bundle.js
  spec/bidders/prebid/price-helper.spec.js
  src/bidders/prebid/prebid-settings.js
  src/bidders/prebid/price-helper.js
Labels: Patch change

#131 ADEN-7483 Applying new changes from app Prebid
  dist/ad-products.amd.js
  dist/ad-products.amd.js.map
  dist/ad-products.css
  dist/ad-products.css.map
  dist/ad-products.global.js
  dist/ad-products.global.js.map
  dist/ad-products.js
  dist/ad-products.js.map
  dist/bidders.amd.js
  dist/bidders.global.js
  dist/bidders.js
  dist/global-bundle.js
  maintenance/build-bundle.sh
  package-lock.json
  package.json
  spec/bidders/prebid/adapters/appnexus-ast.spec.js
  src/bidders/a9/index.js
  src/bidders/index.js
  src/bidders/prebid/adapters/appnexus-ast.js
  src/bidders/prebid/adapters/appnexus.js
  src/bidders/prebid/index.js
  src/bidders/prebid/prebid-helper.js
  src/bidders/prebid/prebid-settings.js
  src/index.js
Labels: Minor change

#147 ADEN-7483 Remove unused bidders window export
  examples/bidders/a9/script.js
  examples/bidders/prebid/script.js
  examples/bidders/reusable-prebid/script.js
  examples/templates/outstream/script.js
  webpack.config.js
Labels: Minor change

#148 ADEN-7566 Update dependencies
  package-lock.json
  package.json
Labels: Patch change

#151 ADEN-7603 Extract prebid lib from main bundle
  examples/bidders/reusable-prebid/script.js
  examples/context.js
  maintenance/build-bundle.sh
  package.json
  src/bidders/index.js
  src/bidders/prebid/index.js
  webpack.config.js
Labels: Major change

#153 ADEN-7603-2 Update dependencies
  package-lock.json
Labels: Major change
