Repository Wikia/ad-products, pull requests merged in 2018-05, with the labels that each got.

#94 ADEN-7004 Adds global bundle
  dist/global-bundle.js
  package.json
Labels: Minor change

#95 ADEN-7004 Update dependencies
  package-lock.json
  package.json
Labels: Minor change

#96 ADEN-7004 Fix global-bundle
  package.json
Labels: Patch change

#97 ADEN-7104 Update dependencies
  package-lock.json
  package.json
Labels: Patch change

#98 ADEN-7004 Update ad-engine
  package-lock.json
  package.json
Labels: Patch change

#102 ADEN-7133 Fixes precision in lABrador
  spec/utils/geo.spec.js
  src/utils/geo.js
Labels: Patch change

#101 ADEN-7155 Rename opt out to opt in
  examples/context.js
  spec/utils/npa.spec.js
  src/utils/npa.js
Labels: Major change

#103 ADEN-7180 Update dependencies
  package-lock.json
  package.json
Labels: Major change
